### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by tsukachu** [cypress-io/cypress-webpack-preprocessor#32]
- Operating System: macOS High Sierra (10.13.6)
- Cypress Version: 3.1.0
- Browser Version:

### Is this a Feature or Bug?

I found a `DeprecationWarning` .
Bug???

### Current behavior:

It was found when the command was executed with the following settings.

`package.json`
```
{
...
  "scripts": {
    ...
    "test:e2e": "vue-cli-service test:e2e",
    ...
  },
...
}
```
```
$ yarn test:e2e --headless
```

stack trace when executed.
```
(node:6017) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at Object.handler (/Users/tsukachu/workspace/private/vue/livue/node_modules/@cypress/webpack-preprocessor/index.js:147:14)
    at invoke (/Users/tsukachu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:16:16)
    at /Users/tsukachu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:48:16
    at tryCatcher (/Users/tsukachu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/tsukachu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/re
lease/method.js:39:29)
    at Object.wrapChildPromise (/Users/tsukachu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:47:28)
    at Object.wrap (/Users/tsukachu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/preprocessor.js:25:8)
    at execute (/Users/tsukachu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:69:20)
    at EventEmitter.ipc.on (/Users/tsukachu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:125:5)
    at emitThree (events.js:135:13)
    at EventEmitter.emit (events.js:216:7)
    at process.<anonymous> (/Users/tsukachu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:25:29)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

ref: https://github.com/cypress-io/cypress-webpack-preprocessor/blob/master/package.json#L65

### Desired behavior:
`DeprecationWarning` is not output.

### How to reproduce:
Please refer to `Current behavior`

### Additional Info (images, stack traces, etc)
![2018-10-22 20 08 59](https://user-images.githubusercontent.com/8770048/47289591-6cfe8e00-d636-11e8-82a3-7de052151c0e.png)

**Comment by chrisbreiding** [comment]
Version `3.0.1` has been published to NPM. The full release note can be found at [cypress-webpack-preprocessor/releases/tag/v3.0.1](https://github.com/cypress-io/cypress-webpack-preprocessor/releases/tag/v3.0.1).

**Tip:** safely upgrade dependency @cypress/webpack-preprocessor in your project using [next-update](https://github.com/bahmutov/next-update)
