### ISSUE TITLE
reject is not defined

### ISSUE THREAD

**Issue by HugoGiraudel** [cypress-io/cypress-webpack-preprocessor#7]
- Operating System: macOS 10.12.6
- Cypress Version: 1.1.0
- Browser Version: n/a

### Is this a Feature or Bug?

A bug.

### Current behavior:

Opening Cypress results in:

```
ReferenceError: reject is not defined
    at EventEmitter.<anonymous> (/Users/hugo/Sites/goldfish/node_modules/cypress/dist/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:81:18)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.<anonymous> (/Users/hugo/Sites/goldfish/node_modules/cypress/dist/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:23:29)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Desired behavior:

Not a crash. :)

### How to reproduce:

Set up the following plugin file:

```
const webpack = require('@cypress/webpack-preprocessor')

module.exports = on => {
  on('file:preprocessor', webpack())
}
```

### Additional Info (images, stack traces, etc)

Using `import` instead of `require` fails the same way.

**Comment by chrisbreiding** [comment]
The error you're seeing is actually in Cypress itself, so I'm moving this to the Cypress repo. We'll be releasing a patch (1.1.1) later today with the fix.

However, there is an error underneath that's overshadowed by the `reject is not defined` error.  Something must be throwing an error in the plugins file. It should become clear once the error handling code is fixed in Cypress itself.

**Comment by chrisbreiding** [comment]
Issue moved to [cypress-io/cypress #934](https://github.com/cypress-io/cypress/issues/934) via [**ZenHub**](https://www.zenhub.com/)
